function replaceModelHelmets()
txdHelmets = engineLoadTXD("IDs/caveira.txd")
engineImportTXD(txdHelmets,1942)
dffHelmets = engineLoadDFF("IDs/caveira.dff",1942)
engineReplaceModel(dffHelmets,1942)
txdHelmets = engineLoadTXD("IDs/coruja.txd")
engineImportTXD(txdHelmets,1943)
dffHelmets = engineLoadDFF("IDs/coruja.dff",1943)
engineReplaceModel(dffHelmets,1943)
txdHelmets = engineLoadTXD("IDs/gato.txd")
engineImportTXD(txdHelmets,1944)
dffHelmets = engineLoadDFF("IDs/gato.dff",1943)
engineReplaceModel(dffHelmets,1944)
txdHelmets = engineLoadTXD("IDs/guaxinim.txd")
engineImportTXD(txdHelmets,1945)
dffHelmets = engineLoadDFF("IDs/guaxinim.dff",1945)
engineReplaceModel(dffHelmets,1945)
txdHelmets = engineLoadTXD("IDs/sacola.txd")
engineImportTXD(txdHelmets,1946)
dffHelmets = engineLoadDFF("IDs/sacola.dff",1946)
engineReplaceModel(dffHelmets,1946)
txdHelmets = engineLoadTXD("IDs/mascote.txd")
engineImportTXD(txdHelmets,1947)
dffHelmets = engineLoadDFF("IDs/mascote.dff",1947)
engineReplaceModel(dffHelmets,1947)
txdHelmets = engineLoadTXD("IDs/cavalo.txd")
engineImportTXD(txdHelmets,1948)
dffHelmets = engineLoadDFF("IDs/cavalo.dff",1948)
engineReplaceModel(dffHelmets,1948)
txdHelmets = engineLoadTXD("IDs/capacete.txd")
engineImportTXD(txdHelmets,1949)
dffHelmets = engineLoadDFF("IDs/capacete.dff",1949)
engineReplaceModel(dffHelmets,1949)
end addEventHandler("onClientResourceStart",getResourceRootElement(getThisResource()),replaceModelHelmets)
function cancelEventEvent()cancelEvent()end 

